export type {
  CatalogRepository,
  CatalogRepositoryError,
  CatalogResult,
  CursorPosition,
  PageQueryParams,
  PagedResult,
  // Vocabularies
  TitleKind,
  ProductionStatus,
  RecordStatus,
  CreditCategory,
  CreditDepartment,
  ReleaseKind,
  TechnicalSpec,
  ConnectionKind,
  CompanyKind,
  CompanyRole,
  ImageKind,
  VideoKind,
  // Records
  Title,
  TitleAka,
  Genre,
  TitleGenre,
  TitleReleaseDate,
  TitleCertificate,
  TitleLocation,
  TitleBoxOffice,
  TitleTechnicalSpec,
  TitleExternalId,
  TitleConnection,
  Person,
  Credit,
  TitleCredit,
  PersonCredit,
  KnownForEntry,
  Season,
  Episode,
  Company,
  TitleCompany,
  Keyword,
  TitleKeyword,
  Image,
  Video,
  // Inputs
  CreateTitleInput,
  UpdateTitleInput,
  CreatePersonInput,
  UpdatePersonInput,
  CreateCreditInput,
  UpsertEpisodeInput,
  CreateImageInput,
  AttachImageInput,
  CreateVideoInput,
  CreateCompanyInput,
  TitleListFilters,
  CreditListFilters,
} from "./types.js";

export {
  TITLE_KINDS,
  PRODUCTION_STATUSES,
  RECORD_STATUSES,
  CREDIT_DEPARTMENTS,
  RELEASE_KINDS,
  TECHNICAL_SPECS,
  CONNECTION_KINDS,
  CONNECTION_INVERSE,
  COMPANY_KINDS,
  COMPANY_ROLES,
  IMAGE_KINDS,
  VIDEO_KINDS,
} from "./types.js";

export { createCatalogRepository } from "./repository.js";
export { sortTitleFor, sortNameFor, slugify } from "./normalize.js";
